### ISSUE TITLE
2nd place winner claiming 1st place

### ISSUE THREAD

**Issue by orishu** [hola/challenge_linked_list#3]
Hi, as I've mentioned in emails, the winning solution is not as fast the the original implementation, therefore it shouldn't have been awarded the 4 points on speed. I don't care about the extra $500, requesting to correct the scoreboard.
Thanks
Ori

**Comment by feldgendler** [comment]
When I run the benchmark that came with the winning solution (GENERIC #1 below), I see this:

```
Performance test has been started ... please wait
ORIGINAL    x 9,780,309 ops/sec ±2.24% (96 runs sampled)
GENERIC #1  x 10,288,250 ops/sec ±0.41% (99 runs sampled)
GENERIC #2  x 19,934,332 ops/sec ±0.77% (99 runs sampled)

Performance test has been successfully completed!
Solution #1 faster than original in 1.05 times
Solution #2 faster than original in 2.04 times

Memory test has been started ... please wait
Memory test has been successfully completed!
Heap Dump Snapshot has been successfully created and can be profiled
[./snapshots/snapshot.heapsnapshot]
```

Node.js v0.10.40

**Comment by orishu** [comment]
Come on!
That's because his "original" implementation isn't _linklist.js! it's also slower than the real original.
I extracted his solution and compared it to the real original, it's almost 2x slower. I've sent that code as attachment to Derry.
This issue shouldn't be closed.

**Comment by feldgendler** [comment]
Can you elaborate on how what he calls “original” is different from the original _linklist.js?

**Comment by orishu** [comment]
Ok I incorrectly assumed that the original isn't the real original because the code was 2x slower in my benchmark. So the problem isn't in the original implementation, it's in his test suite, that calls remove() after each append() - this way the list never really grows beyond one element - bogus test.

Here's there output I got on his code:

    Performance test has been started ... please wait
    ORIGINAL    x 10,598,757 ops/sec ±1.09% (96 runs sampled)
    GENERIC #1  x 10,894,709 ops/sec ±0.80% (96 runs sampled)
    GENERIC #2  x 21,204,827 ops/sec ±1.13% (94 runs sampled)

And here's the output I'm getting when I comment out the "remove()"s:

    Performance test has been started ... please wait
    ORIGINAL    x 3,599,596 ops/sec ±18.22% (69 runs sampled)
    FATAL ERROR: JS Allocation failed - process out of memory

As you can see, the original implementation completes successfully (3x slower than the append+remove test, though).
The "Generic #1" solution crashed on memory. So I commented out the "original" benchmark so the "generic 1" will run first:, and got:

    Performance test has been started ... please wait
    GENERIC #1  x 2,222,780 ops/sec ±19.76% (62 runs sampled)
    FATAL ERROR: JS Allocation failed - process out of memory

So "generic 1" runs in 62% of the speed of the original.

When I commented out generic 1 as well I got this for generic 2:

    Performance test has been started ... please wait
    GENERIC #2  x 3,015,967 ops/sec ±19.81% (54 runs sampled)

which is 84% of the speed.

**Comment by feldgendler** [comment]
Indeed, if you change the benchmark, it changes the outcome. However, the scoring rule was formulated as follows:

> We ran all supplied performance tests. Whenever the test results showed that the submitted solution is not slower than the original code, the author got **4 points**.

I agree that this is not the most fair way to award points when every submission gets tested with a different benchmark. However, I cannot change the final scores without also changing this rule and re-benchmarking *all* submissions (for which one would have to hand-adapt each of them to be tested because the rules did not strictly require a compatible API).

We're going to learn from this in the future challenges and always mandate a well-specified API, so that submissions can be fairly tested with our own test suite.

By the way, I've added a note to README.md to recognize your original approach to the challenge.

**Comment by orishu** [comment]
Thanks for your response, I understand the situation.
However, quoting the challenge web page, the challenge was "to make it generic, while not reducing performance". You don't need to re-evaluate all solutions in order to disqualify one that clearly doesn't meet a basic requirement, not to mention the API change...

Anyways, thanks for adding that note!
